name: Continuous Integration

on:
    push:
        branches: [ "main" ]
        paths: &paths
            - "**/*.rs"
            - "**/*.toml"
            - "Dockerfile"
            - ".github/workflows/**"
    pull_request:
        branches: [ "main" ]
        paths: *paths

permissions:
    contents: read

jobs:
    ci:
        name: Test and Build
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v7

            -   name: Setup Rust
                uses: dtolnay/rust-toolchain@stable
                with:
                    components: rustfmt, clippy

            -   name: Cache Dependencies
                uses: Swatinem/rust-cache@v2

            -   name: Format Check
                run: cargo fmt --check

            -   name: Run Lints
                run: cargo clippy -- -D warnings

            -   name: Run Tests
                run: cargo test

            -   name: Build Release
                run: cargo build --release
